### PR TITLE
utilize the Filter mechanism to only read required partitions

### PR DESCRIPTION
**Pull request by nahguam**

### CODE REVIEW

**Comment by cwensel** [comment]
I think we need to know the partition fields that are relevant to the filter. Think argument selector that selects the fields from the partition fields. And allowing for more than one filter per unique argument selector.

the question then becomes should this be a ctor argument or a user level #add (or planner level #present) method so we can maintain a collection of argument selector, filter pairs.

the justification for this is having the query planner find filters that apply to the partition fields, and to then present those filters to the source Partition Tap on the fly, instead of requiring a user to build a Tap with the filters embedded. (the planner would present a complete collection to each PartitionTap instance, and should notify if any are already set) 

should also have the arguments/filters included in the #equals() call.

also, can you base this on wip-3.1, that will help, it didn’t apply there (3.0 did fine).

**Comment by cwensel** [comment]
I’m pretty aware of the issues. we would only push down filters that were applicable -- not all filters. partitioning on date, for example, and filtering on date, would be a very useful use-case — and not couple the Tap to the business logic of the given pipe assembly (by explicitly giving it a Filter vs having the filter naturally apply in the assembly)

regardless, for re-usability, requiring all Filters to apply against Fields.ALL (resolved to the partition fields) is brittle, Filters should be paired with the arguments they apply to (where Fields.ALL is the default). this would allow a natural composability of Filters, vs a special case Filter for the partition.

**Comment by nahguam** [comment]
Hi Chris,

I see what you mean with respect to maintaining a collection of argument selector / `Filter` pairs. It does make more sense. For the planner push down to the `PartitionTap`, I'll need to understand the planner mechanics a bit more. I assume it keeps track of argument & output selectors and can interrogate the declared/results `Fields`. We could 'walk the DAG' from the `PartitionTap` identifying candidate `Filter`s that we can apply and stop when the situation become ambiguous, i.e. a partition field may have been altered within an `Operation`.

I propose to tackle this in two steps:
1. In this pull request, refactor the current changes to use an #add method for argument selector / `Filter` pairs instead of the ctor and include in #equals.
2. In a separate pull request look at getting the planner to dynamically add the argument selector / `Filter` pairs to the `PartitionTap`.

With respect to basing this on wip-3.1, do you mean closing this PR, rebasing against cwensel/wip-3.1 branch and opening a new PR there?

**Comment by cwensel** [comment]
I wasn't asking for the planner changes, that will take some deep work. 

I think we just need the PartitionTap to handle argument/filter pairs.

and I think it reasonable that they be only provided on the constructor. Taps/Schemes aren't really immutable but for the most part are (the source/sink fields can be changed at plan time, with the proposal that filters added at plan time in the future).

**Comment by nahguam** [comment]
I've made the change so we have a `List` of `Filter`s and an argument selector is bound to each `Filter`. It's an add method only. I decided not to keep the constructor.

I understand you weren't asking for the planner changes right now. Though, I have had a look into it. In `FlowElementGraph#initialize` (and the last constructor) after `#verifyGraph`. We could start by looping through `#getSources` looking for instances of `BasePartitionTap` then start walking the `#outgoingEdgesOf` performing the complex resolution and validation of `Fields`. I did get a very simple example working. Anyway, perhaps this discussion should be started in a different thread.

With respect to basing the current changes on wip-3.1, do you mean closing this PR, rebasing against cwensel/wip-3.1 branch and opening a new PR there?

**Comment by nahguam** [comment]
Hi Chris, Have you had a chance to review this?

**Comment by cwensel** [comment]
No sorry, in the middle of cutting a product release and bugs in 3.0. and I'm OOO next week. sorry for the  delays.

**Comment by nahguam** [comment]
I've rebased on cwensel/wip-3.1

**Comment by nahguam** [comment]
Hi, just a gentle nudge to see if you've managed to take another look at this?

**Comment by cwensel** [comment]
I need some time to think through this. 

argument selectors do not require a type, they are simply a pattern, not a declaration. types are pulled from the incoming resolved stream, in this case partitionFields which may or may not have types. 

so instead of using the raw `argumentSelector` as the argument TupleEntry delcarator, they need to be resolved against the `partitionFields`.

That is, its valid to have a Fields.ALL selector, but that resolves to new Fields( 'year', 'month' ) at runtime which is then passed to the Filter instance.

re the planner optimization, i would recommend a rule at the PostResolveAssembly phase, https://github.com/cwensel/cascading/blob/92d0b1f0c5e7bcb7817ab8411af8b470f4b63090/cascading-core/src/main/java/cascading/flow/planner/rule/PlanPhase.java#L35-35

which is immediately prior to field resolution that is required to know which operation is doing what to whom.

most rules are implemented by our isomorphic graph matching rule engine (to minimize the non-linear runtimes of large complex graphs against naive search algorithms) but a simple depth first search would be sufficient to identify and collect predicate filters to pass to a given source. the search would stop once all the partition fields have been mutated for a given source.

Each `Each` harboring a argument selector and Filter could then be removed from the Graph, with care take to use the resolved argument selector.

**Comment by cwensel** [comment]
Actually, it simplified things a little. see https://github.com/cwensel/cascading/tree/wip-3.1-partitionfilter

if you can test that out, i'll run regressions on this end.

the only questionable change is that addPartitionFilter will throw a FieldsResolverException now, but it can be argued this should be wrapped with an IllegalArgumentException.

**Comment by nahguam** [comment]
Looks good. Thinking about it, FieldsResolverException would be more consistent than IllegalArgumentException.

**Comment by cwensel** [comment]
ok, pushing to wip-3.1 and closing. thanks!

**Pull request closed without merging**
