### PR TITLE
In some cases,readStateFromDistCache can not throw the correct exception...

### PR DESCRIPTION
**Pull request by d0ngw**
... because exceptions may be swallowed.

### CODE REVIEW

**Comment by cwensel** [comment]
under what circumstances is this an issue?

**Comment by d0ngw** [comment]
@cwensel  
We run the  application on security hadoop cluster, but we set the wrong config for the  child job jvm opts.
This will cause the reader fail to create,and the exception is NPE,but not the Kerberos exception,it took us a long time to locate the real problem.

**Comment by cwensel** [comment]
ok, fair enough. I think we resolved issues of exceptions being eaten in 2.2, but i'll go ahead and eat the .close exception in 2.2. closing this, but will put similar code in the next 2.2 wip.

**Comment by d0ngw** [comment]
@cwensel 

Thanks for your reply. 

Could you review another commit 3a2db4a ? 

When we use non-strict mode to process the data, the data is produced by  different application version,the map job will generate too much logs.

**Comment by cwensel** [comment]
i've downgraded both the parse and coerce messages to debug if they aren't enforced.

**Comment by d0ngw** [comment]
I think if only change the log level from warn to debug it will create too much unused message string object,this will  waste the cpu to create million objects and increase the gc workload if the input data is too big.

**Comment by cwensel** [comment]
is this acceptable
https://github.com/cwensel/cascading/commit/a1560a6b245e11c338f29456655dd25a43575089

**Comment by d0ngw** [comment]
Yes,the new commit is pretty well.
Thanks.

**Pull request closed without merging**
